- hosts: all  
  become: yes
  handlers:
    - name: "restart Nginx"
      service:
        name: nginx
        state: restarted
  tasks:
    - name: "Roda: sudo apt update"
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia
    
    - name: "Instala pacotes em lote"
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - nginx
        - unzip

    - name: "Fazendo downlaod do bootstrap"
      get_url:
        url: "https://github.com/startbootstrap/startbootstrap-sb-admin-2/archive/gh-pages.zip"
        dest: "/tmp/gh-pages.zip"
    
    - name: "Fazendo descompactação dos arquivos do bootstrap"
      unarchive:
        src: "/tmp/gh-pages.zip"
        dest: "/var/www/html"
        remote_src: yes

    - name: "Trocando pasta do render do niginx"
      become: yes
      copy:
        src: "exercicio/nginx/default"
        dest: "/etc/nginx/sites-available/default"
      notify:
        - "restart Nginx"

    - shell: cat /etc/nginx/sites-available/default|grep -i www
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "

    